render templates for aggregator and executor

diff --git a/.devkit/scripts/run b/.devkit/scripts/run
--- a/.devkit/scripts/run
+++ b/.devkit/scripts/run
@@ -20,9 +20,6 @@ ensureJq
 ensureYq
 ensureGomplate
 
-
-echo $CONTEXT | jq '.'
-
 ENVIRONMENT=$(echo "$CONTEXT" | jq -r '.context.name')
 if [ "$ENVIRONMENT" == "null" ] || [ -z "$ENVIRONMENT" ]; then
     log "Error: Missing name (environment) in context"
@@ -32,20 +29,6 @@ hourglassContextConfigPath="$( dirname "${BASH_SOURCE[0]}" )/../../.hourglass/co
 contextConfig="$(cat $hourglassContextConfigPath | yq -o json)"
 
 log "Starting AVS components for environment: $ENVIRONMENT"
-
-# extract aggregator and executor config values
-function extractOperatorContext() {
-    local address=$1
-
-    local operatorCount=$(echo $CONTEXT | jq -r ".context.operators | length")
-    for i in $(seq 0 $((operatorCount - 1))); do
-        local operatorAddress=$(echo $CONTEXT | jq -r ".context.operators[$i].address")
-        if [ "$operatorAddress" == "$address" ]; then
-            echo $(echo $CONTEXT | jq -r ".context.operators[$i]")
-            return
-        fi
-    done
-}
 
 function readOperatorBlsKeystore() {
     cat $(realpath $1) | jq -r '.'
@@ -57,28 +40,30 @@ function loadBlsKeysForAllOperators() {
         local operatorAddress=$(echo $CONTEXT | jq -r ".context.operators[$i].address")
         local blsKeystorePath=$(echo $CONTEXT | jq -r ".context.operators[$i].bls_keystore_path")
         local blsKeyContents=$(echo $(readOperatorBlsKeystore $blsKeystorePath) | jq -c '.')
-        echo "blsKeyContents: $blsKeyContents"
         # set the bls key contents in the context as a raw string
         CONTEXT=$(echo $CONTEXT | jq --argjson blsKeyContents "$blsKeyContents" ".context.operators[$i].bls_key_contents = \$blsKeyContents")
     done
 }
 
-# aggregatorInfo=$(extractOperatorContext $(echo $contextConfig | jq -r '.aggregator.operators[0].address'))
-# echo "aggregator info: $aggregatorInfo"
-#
-# blsKeyContents=$(readOperatorBlsKeystore $(echo $aggregatorInfo | jq -r '.bls_keystore_path'))
-# echo "bls key contents: $blsKeyContents"
 loadBlsKeysForAllOperators
 
 # set aggregator and executor
 CONTEXT=$(echo $CONTEXT | jq --argjson contextConfig "$contextConfig" '.aggregator = $contextConfig.aggregator')
 CONTEXT=$(echo $CONTEXT | jq --argjson contextConfig "$contextConfig" '.executor = $contextConfig.executor')
 
-echo "PRE RENDER\n"
-echo $CONTEXT | jq '.'
-echo $CONTEXT | gomplate -f .hourglass/config/aggregator-template.yaml -d 'ctx=stdin:/?type=application/json'
+deployedContracts=$(echo $CONTEXT | jq -r '.context.deployed_contracts')
+if [ "$deployedContracts" == "null" ] || [ -z "$deployedContracts" ]; then
+    log "Error: Need to deploy contracts. Please run 'devkit avs devnet start'"
+    exit 1
+fi
+
+#echo "CONTEXT....\n\n"
+#echo $CONTEXT | jq '.'
+
+echo $CONTEXT | gomplate -f .hourglass/config/aggregator-template.yaml -d 'ctx=stdin:/?type=application/json' > .hourglass/config/aggregator.yaml
+echo $CONTEXT | gomplate -f .hourglass/config/executor-template.yaml -d 'ctx=stdin:/?type=application/json' > .hourglass/config/executor.yaml
 
 # Run the Aggregator and Executor in docker containers
-# ./.hourglass/scripts/run.sh
+./.hourglass/scripts/run.sh
 
 log "AVS components started successfully." 
